services:
  unclassified-photos:
    build: .
    image: fytpet/unclassified-photos
    container_name: unclassified-photos
    restart: unless-stopped
    depends_on:
    - redis
    ports:
    - "${PORT}:${PORT}"
    volumes:
    - ./logs:/app/logs
    env_file:
    - .env
  redis:
    image: "redis:7.0-alpine"
    container_name: redis
    restart: unless-stopped
    ports:
    - "6379:6379"
    volumes:
    - ./data:/data
  nginx:
    image: "nginx:1.25"
    container_name: nginx
    restart: unless-stopped
    ports:
    - "80:80"
    - "443:443"
    volumes:
    - ./nginx.conf:/etc/nginx/templates/nginx.conf.template
    - /etc/letsencrypt:/etc/letsencrypt
    environment:
      NGINX_ENVSUBST_OUTPUT_DIR: /etc/nginx
    env_file:
      - .env
