services:
  unclassified-photos:
    build: .
    image: unclassified-photos
    container_name: unclassified-photos
    restart: unless-stopped
    ports:
    - "443:${HTTPS_PORT}"
    - "80:${HTTP_PORT}"
    volumes:
    - ./logs:/app/logs
