name: Integration Pipeline

on:
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: npm ci
    - name: Run validations
      run: npm run validate
    - name: Build the Docker image
      run: docker build .
